# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Automation Admin
subtitle: "A blog on engineering and administering various Automation technologies"
email: admin@automationadmin.com
description: A blog on engineering and administering various Automation technologies
github_username: gerryw1389
github_repository: https://github.com/gerryw1389/gerryw1389.github.io
minimal_mistakes_skin: dirt # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
lunr:
  search_within_pages: true

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

remote_theme: mmistakes/minimal-mistakes@4.16.5

# Outputting
permalink: "pretty"
paginate: 20 # amount of posts to show
paginate_path: /page:num/
timezone: "US/Central" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : ""
  avatar : "/assets/images/gerryw.png"
  bio    : ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gerryw1389"
    - label: "Reddit"
      icon: "fab fa-reddit-alien"
      url: "https://www.reddit.com/user/gerryw1389/"
    - label: "Popular Posts"
      icon: "fas fa-fw fa-link"
      url: "https://automationadmin.com/2016/02/popular-posts"
    - label: "Bookmarks"
      icon: "fas fa-bookmark"
      url: "https://automationadmin.com/2016/02/bookmarks"

footer:
  links:
    - label: "Home"
      icon: "fas fa-fw fa-link"
      url: "https://automationadmin.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gerryw1389"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single # was compress
      author_profile: true
      read_time: true
      comments: false
      sidebar:
        nav: "categories"
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-73268434-2"
    anonymize_ip: false # default
