# Ref => https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.20.0"
minimal_mistakes_skin: dirt # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

# Reading Files
include:
  - _pages

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true

# Site Settings
locale: "en-US"
title: "Automation Admin"
subtitle: "A blog on engineering and administering various Automation technologies"
description: "A blog on engineering and administering various Automation technologies"
name: "gerryw1389"
url: "https://automationadmin.com"
repository: "gerryw1389/gerryw1389.github.io"

# Search
search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: google # lunr (default), algolia, google
google:
  search_engine_id: 43ce0de971d0f4f85
  instant_search: false # false (default), true

# Comments
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-73268434-2"
    anonymize_ip: false # default

# Outputting
permalink: "pretty"
paginate: 20 # amount of posts to show
paginate_path: /page:num/
timezone: "US/Central" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Author
author:
  name: ""
  avatar: "/assets/images/gerryw.png"
  bio: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gerryw1389"
    - label: "Reddit"
      icon: "fab fa-reddit-alien"
      url: "https://www.reddit.com/user/gerryw1389/"
    - label: "Popular Posts"
      icon: "fas fa-fw fa-link"
      url: "https://automationadmin.com/2016/02/popular-posts"
    - label: "Bookmarks"
      icon: "fas fa-bookmark"
      url: "https://automationadmin.com/2016/02/bookmarks"

# Site footer
footer:
  links:
    - label: "Home"
      icon: "fas fa-fw fa-link"
      url: "https://automationadmin.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gerryw1389"

# Archive Pages
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      sidebar:
        nav: "categories"
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
